spring.application.name = simgap-daq

spring.datasource.url = jdbc:postgresql://localhost:5432/SIMGAP
spring.datasource.username = postgres
spring.datasource.password = Febrero2025*+

spring.jpa.hibernate.ddl-auto = create
app.test-data.enabled=true