### Listar todos los dispositivos
GET http://localhost:8080/api/v1/dispositivos

### Buscar un dispositivo por nombre exacto
GET http://localhost:8080/api/v1/dispositivos/nombre/DAQ-RTG01

### Buscar dispositivos que contengan un texto en el nombre
GET http://localhost:8080/api/v1/dispositivos/buscar/RTG

### Crear un dispositivo
POST http://localhost:8080/api/v1/dispositivos
Content-Type: application/json

{
  "name": "DAQ-RTG01",
  "addressIp": "192.168.1.10",
  "mac": "AA:BB:CC:DD:EE:01",
  "craneName": "RTG01",
  "rack":0,
  "slot":1,
  "isOperational": true
}

### Actualizar el dispositivo con ID 1
PUT http://localhost:8080/api/v1/dispositivos/1
Content-Type: application/json

{
  "name": "DAQ-RTG01",
  "addressIp": "192.168.1.20",
  "mac": "AA:BB:CC:DD:EE:01",
  "craneName": "RTG01",
  "rack": 0,
  "slot": 1,
  "isOperational": false
}

### Eliminar el dispositivo con ID 1
DELETE http://localhost:8080/api/v1/dispositivos/1
